# Generated by Django 5.0.1 on 2026-03-04 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد المستحق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(editable=False, max_length=12, unique=True, verbose_name='رقم الفاتورة')),
                ('status', models.CharField(choices=[('completed', 'مكتملة'), ('held', 'معلقة'), ('cancelled', 'ملغاة'), ('returned', 'مرتجعة')], default='completed', max_length=20, verbose_name='الحالة')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('card', 'بطاقة'), ('credit', 'آجل'), ('transfer', 'تحويل بنكي'), ('mixed', 'مختلط')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المجموع الفرعي')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ الخصم')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المدفوع')),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الباقي')),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الفكة')),
                ('profit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الربح')),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='التكلفة')),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='نقداً')),
                ('card_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بطاقة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الكاشير')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'فاتورة مبيعات',
                'verbose_name_plural': 'فواتير المبيعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(default='قطعة', max_length=50, verbose_name='الوحدة')),
                ('unit_factor', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر البيع')),
                ('cost_price', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='سعر التكلفة')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الخصم')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.product', verbose_name='المنتج')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleinvoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'بند فاتورة',
                'verbose_name_plural': 'بنود الفواتير',
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(editable=False, max_length=12, unique=True, verbose_name='رقم المرتجع')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('total_refund', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المسترجع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.saleinvoice', verbose_name='الفاتورة الأصلية')),
            ],
            options={
                'verbose_name': 'مرتجع',
                'verbose_name_plural': 'المرتجعات',
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.product', verbose_name='المنتج')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesreturn', verbose_name='المرتجع')),
            ],
        ),
    ]
