# Generated by Django 5.0.1 on 2026-03-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='invoice_id',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='return_id',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم المرتجع'),
        ),
    ]
