# Generated by Django 5.0.1 on 2026-03-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التسلسل')),
                ('last_value', models.BigIntegerField(default=0, verbose_name='آخر قيمة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تسلسل النظام',
                'verbose_name_plural': 'تسلسلات النظام',
            },
        ),
    ]
