# Generated by Django 5.0.1 on 2026-03-04 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_id', models.CharField(editable=False, max_length=12, unique=True, verbose_name='رقم التقرير')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('damage_date', models.DateField(verbose_name='تاريخ التلف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('total_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الخسارة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports_approved', to=settings.AUTH_USER_MODEL, verbose_name='اعتمدها')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports_created', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
            ],
            options={
                'verbose_name': 'تقرير تالف',
                'verbose_name_plural': 'تقارير التالف',
                'ordering': ['-damage_date'],
            },
        ),
        migrations.CreateModel(
            name='DamageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية المتلفة')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='تكلفة الوحدة')),
                ('total_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الخسارة')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.product', verbose_name='المنتج')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='damages.damagereport', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'بند تلف',
                'verbose_name_plural': 'بنود التلف',
            },
        ),
    ]
