# Generated by Django 5.0.1 on 2026-03-04 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'بيع'), ('purchase', 'شراء'), ('return_sale', 'مرتجع بيع'), ('return_purchase', 'مرتجع شراء'), ('adjustment', 'تعديل يدوي'), ('stocktake', 'جرد مخزني'), ('damage', 'تالف/هالك')], max_length=20, verbose_name='نوع الحركة')),
                ('quantity_change', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='تغيير الكمية')),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية بعد الحركة')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='المرجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='books.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حركة مخزنية',
                'verbose_name_plural': 'حركات المخزن',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100, verbose_name='اسم جلسة الجرد')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
            ],
            options={
                'verbose_name': 'جرد مخزني',
                'verbose_name_plural': 'عمليات الجرد',
            },
        ),
        migrations.CreateModel(
            name='StockTakingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='كمية النظام')),
                ('actual_qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية الفعلية')),
                ('difference', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الفرق')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.product', verbose_name='المنتج')),
                ('stocktaking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktaking', verbose_name='جلسة الجرد')),
            ],
            options={
                'verbose_name': 'عنصر جرد',
                'verbose_name_plural': 'عناصر الجرد',
            },
        ),
    ]
