# Generated by Django 5.0.1 on 2026-03-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_migrate_categories_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
