# Generated by Django 5.0.1 on 2026-03-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_old_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='books.category', verbose_name='الفئة الرئيسية'),
        ),
    ]
