# Generated by Django 5.0.1 on 2026-03-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_add_primary_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_category',
        ),
    ]
