# Generated by Django 5.0.1 on 2026-03-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_primary_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
