# Generated by Django 5.0.1 on 2026-03-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم المنتج'),
        ),
    ]
