# Generated by Django 5.0.1 on 2026-03-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تخفيض القطعة %'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_package',
            field=models.BooleanField(default=False, verbose_name='يحتوي عبوة'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تخفيض العبوة %'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_qty',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='عدد القطع داخل العبوة'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ضريبة العبوة %'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='نوع العبوة'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ضريبة القطعة %'),
        ),
    ]
