# Generated by Django 5.0.1 on 2026-03-05 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_product_discount_rate_product_has_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='package_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True, verbose_name='سعر شراء العبوة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_qty',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='عدد القطع داخل العبوة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_selling_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True, verbose_name='سعر بيع العبوة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='سعر البيع'),
        ),
    ]
