# Generated by Django 5.0.1 on 2026-03-05 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_product_package_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تخفيض القطعة %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_purchase_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='آخر سعر شراء'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='أقل سعر مسموح'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تخفيض العبوة %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ضريبة العبوة %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='هامش الربح %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ضريبة القطعة %'),
        ),
    ]
