# Generated by Django 5.0.1 on 2026-03-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_product_discount_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المؤلف'),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(blank=True, choices=[('ar', 'العربية'), ('en', 'الإنجليزية'), ('fr', 'الفرنسية'), ('es', 'الإسبانية'), ('tr', 'التركية'), ('other', 'أخرى')], default='ar', max_length=10, null=True, verbose_name='اللغة'),
        ),
        migrations.AddField(
            model_name='product',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الصفحات'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('book', 'كتاب'), ('general', 'منتج عادي')], default='book', max_length=20, verbose_name='نوع المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم المنتج/الكتاب'),
        ),
    ]
