# Generated by Django 5.0.1 on 2026-03-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchaseinvoice_invoice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='unit_factor',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='unit_name',
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='is_package',
            field=models.BooleanField(default=False, verbose_name='شراء بالعبوة'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='package_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر شراء العبوة'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='package_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='عدد العبوات'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='package_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر بيع العبوة'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='pieces_per_package',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='قطع/عبوة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية (بالقطع)'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='suggested_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر بيع القطعة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر شراء القطعة'),
        ),
    ]
